import React, { useEffect, useRef, useState } from "react";
import Layout from "../components/Layout";
import { Button, Input } from "../components/FormElements";
import { useTranslation } from "react-i18next";
import { signInWithEmail, signUpWithEmail } from "../services/authService";

type AuthMode = "login" | "signup";

type ChatMessage = {
  from: "user" | "bot";
  text: string;
};

const LaiTurnerDemoPage: React.FC = () => {
  const { t } = useTranslation();
  const [mode, setMode] = useState<AuthMode>("signup");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loadingAuth, setLoadingAuth] = useState(false);
  const [authMessage, setAuthMessage] = useState<string | null>(null);
  const [authError, setAuthError] = useState<string | null>(null);

  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    {
      from: "bot",
      text:
        "Welcome to the LAI & TURNER demo chat. In a live setup, your immigration, family, and trial clients could reach your team here, while an AI assistant handles level 1 questions and routes complex issues to you in English, Mandarin, Japanese, and German.",
    },
  ]);
  const [chatInput, setChatInput] = useState("");
  const [dictationSupported, setDictationSupported] = useState(false);
  const [dictationStatus, setDictationStatus] = useState("Idle");
  const [dictationError, setDictationError] = useState<string | null>(null);
  const [isListening, setIsListening] = useState(false);
  const [ttsSupported, setTtsSupported] = useState(false);
  const [ttsStatus, setTtsStatus] = useState("Ready");
  const recognitionRef = useRef<SpeechRecognition | null>(null);

  const faqs = [
    {
      question: "What types of clients does Jimmy Lai typically help?",
      answer:
        "Immigrants, founders, professionals, and families who need guidance for visas, trials, business matters, and cross-border issues.",
    },
    {
      question: "Which practice areas could this client portal support?",
      answer:
        "Immigration (family-based, marriage-based, employment-based), criminal defense, family law, estate planning & probate, personal injury, real estate, business & employment.",
    },
    {
      question: "In which languages can you support clients through this portal?",
      answer: "English, Mandarin Chinese, Japanese, German, and Spanish if desired.",
    },
    {
      question: "How could an AI Help Desk help your immigration and family law clients?",
      answer:
        "24/7 intake, FAQs on timelines and required documents, pre-qualification flows, and fast escalation to your attorneys for complex matters.",
    },
    {
      question: "What concrete services would Nexus Support Hub provide to LAI & TURNER?",
      answer:
        "Branded client portal, AI chat, ticketing, knowledge base, and integrations with tools like Lawbrokr or your practice management stack.",
    },
    {
      question: "How is this service typically priced?",
      answer:
        "Monthly subscription calibrated to the firm’s size and usage — no payment links are included in this demo.",
    },
    {
      question: "What does implementation look like for your firm?",
      answer:
        "Discovery workshop, workflow configuration, pilot phase, then optimisation with your attorneys and staff.",
    },
  ];

  const handleAuthSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setLoadingAuth(true);
    setAuthError(null);
    setAuthMessage(null);

    try {
      if (mode === "signup") {
        await signUpWithEmail(email, password, {
          fullName: "LAI & TURNER Client",
          role: "user",
          companyName: "LAI & TURNER",
          lang: "en",
        });
        setAuthMessage(
          "Account created successfully. Please check your inbox to confirm your email, then log in."
        );
        setMode("login");
      } else {
        await signInWithEmail(email, password);
        setAuthMessage("Successfully logged in – this account is now linked to LAI & TURNER.");
      }
    } catch (error: any) {
      setAuthError(error?.message || "An unexpected error occurred.");
    } finally {
      setLoadingAuth(false);
    }
  };

  const handleSendMessage = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!chatInput.trim()) return;

    const userMessage: ChatMessage = { from: "user", text: chatInput.trim() };
    setChatMessages((prev) => [...prev, userMessage]);
    setChatInput("");

    setTimeout(() => {
      const botMessage: ChatMessage = {
        from: "bot",
        text:
          "Thanks for your message. In a production setup, this reply would be generated by your AI Help Desk, pre-trained on LAI & TURNER FAQs and procedures.",
      };
      setChatMessages((prev) => [...prev, botMessage]);
    }, 400);
  };

  useEffect(() => {
    if (typeof window === "undefined") return;
    const synthAvailable = "speechSynthesis" in window && typeof SpeechSynthesisUtterance !== "undefined";
    setTtsSupported(synthAvailable);

    const SpeechRecognitionCtor =
      (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognitionCtor) return;

    const recognition: SpeechRecognition = new SpeechRecognitionCtor();
    recognition.lang = "en-US";
    recognition.continuous = false;
    recognition.interimResults = false;

    recognition.onstart = () => {
      setIsListening(true);
      setDictationStatus("Listening…");
      setDictationError(null);
    };

    recognition.onend = () => {
      setIsListening(false);
      setDictationStatus("Idle");
    };

    recognition.onerror = (event) => {
      setIsListening(false);
      setDictationStatus("Idle");
      setDictationError(event.error ? `Voice capture error: ${event.error}` : "Voice capture error");
    };

    recognition.onresult = (event) => {
      const transcript = Array.from(event.results)
        .map((result) => result[0].transcript)
        .join(" ")
        .trim();
      if (!transcript) return;
      setChatInput((prev) => (prev ? `${prev.trim()} ${transcript}`.trim() : transcript));
      setDictationStatus("Transcribed");
    };

    recognitionRef.current = recognition;
    setDictationSupported(true);

    return () => {
      recognition.stop();
    };
  }, []);

  useEffect(() => {
    if (!ttsSupported) return;
    const lastMessage = chatMessages[chatMessages.length - 1];
    if (!lastMessage || lastMessage.from !== "bot") return;

    const synth = window.speechSynthesis;
    if (!synth) return;

    const utterance = new SpeechSynthesisUtterance(lastMessage.text);
    utterance.lang = "en-US";
    utterance.rate = 1;
    utterance.pitch = 1;

    utterance.onstart = () => setTtsStatus("Playing demo reply");
    utterance.onend = () => setTtsStatus("Ready");
    utterance.onerror = () => setTtsStatus("Playback unavailable");

    synth.cancel();
    synth.speak(utterance);
  }, [chatMessages, ttsSupported]);

  const startDictation = () => {
    if (!dictationSupported || !recognitionRef.current || isListening) return;
    try {
      recognitionRef.current.start();
    } catch (error) {
      setDictationError("Unable to start voice dictation.");
    }
  };

  const stopDictation = () => {
    if (!recognitionRef.current) return;
    recognitionRef.current.stop();
    setIsListening(false);
  };

  return (
    <Layout>
      <div className="min-h-[calc(100vh-5rem)] bg-slate-50 py-10">
        <div className="mx-auto max-w-6xl px-4 space-y-10">
          <section className="space-y-4">
            <div className="inline-flex items-center rounded-full bg-indigo-50 px-4 py-1 text-xs font-semibold uppercase tracking-wide text-indigo-700">
              Demo • Nexus Support Hub × LAI & TURNER Law Firm
            </div>
            <h1 className="text-3xl font-bold text-slate-900 sm:text-4xl lg:text-5xl">
              Client portal & AI Help Desk for
              <span className="text-indigo-600"> immigration, family & trial clients</span>
            </h1>
            <p className="max-w-5xl text-lg text-slate-700">
              Jimmy Lai, JD/MBA, built Lai & Turner Law Firm to “do law differently” for immigrants, founders, families, and clients across Oklahoma and beyond. This page is a personalised demo of how a branded, multilingual client portal could support your intake, FAQs, and ongoing case communication.
            </p>
          </section>

          <section className="grid gap-6 md:grid-cols-2">
            <div className="relative overflow-hidden rounded-3xl border border-slate-800 bg-slate-900 p-6 shadow-xl">
              <div className="pointer-events-none absolute inset-0 text-[120px] font-black uppercase tracking-widest text-slate-700/10">
                <div className="absolute -left-6 top-10 rotate-6">LAI & TURNER</div>
              </div>
              <div className="relative space-y-6 text-white">
                <div className="flex items-center gap-2 rounded-full bg-slate-800/70 p-1 text-sm font-semibold">
                  <button
                    type="button"
                    className={`flex-1 rounded-full px-3 py-2 text-center transition ${
                      mode === "signup"
                        ? "bg-white text-slate-900"
                        : "text-slate-300 hover:text-white"
                    }`}
                    onClick={() => setMode("signup")}
                  >
                    Create account
                  </button>
                  <button
                    type="button"
                    className={`flex-1 rounded-full px-3 py-2 text-center transition ${
                      mode === "login"
                        ? "bg-white text-slate-900"
                        : "text-slate-300 hover:text-white"
                    }`}
                    onClick={() => setMode("login")}
                  >
                    Log in
                  </button>
                </div>

                <div className="space-y-2">
                  <h2 className="text-2xl font-bold">LAI & TURNER client access</h2>
                  <p className="text-sm text-slate-300">
                    Create a demo account or log in to see how LAI & TURNER clients could authenticate in a branded, secure portal.
                  </p>
                </div>

                <form className="space-y-4" onSubmit={handleAuthSubmit}>
                  <Input
                    type="email"
                    required
                    label="Email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    aria-label={t("laiTurner.email", { defaultValue: "Email address" })}
                    className="bg-white/90"
                  />
                  <Input
                    type="password"
                    required
                    label="Password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    aria-label={t("laiTurner.password", { defaultValue: "Password" })}
                    className="bg-white/90"
                  />
                  <Button type="submit" className="w-full" isLoading={loadingAuth}>
                    {mode === "signup" ? "Create account" : "Log in"}
                  </Button>
                </form>

                {authError && (
                  <div className="rounded-xl border border-red-500/60 bg-red-500/10 px-4 py-3 text-sm text-red-100">
                    {authError}
                  </div>
                )}

                {authMessage && (
                  <div className="rounded-xl border border-emerald-400/60 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-100">
                    {authMessage}
                  </div>
                )}

                <p className="text-xs text-slate-400">
                  This is a demo environment. In a live deployment, we can enforce your firm’s security policies (2FA, SSO, IP restrictions, etc.).
                </p>
              </div>
            </div>

            <div className="space-y-6">
              <div className="relative overflow-hidden rounded-3xl border border-slate-800 bg-slate-900 p-6 shadow-xl">
                <div className="pointer-events-none absolute inset-0 text-[100px] font-black uppercase tracking-widest text-slate-700/10">
                  <div className="absolute -right-10 bottom-4 -rotate-6">LAI & TURNER</div>
                </div>
                <div className="relative space-y-4 text-white">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <h2 className="text-xl font-bold">LAI & TURNER – Client Support Chat</h2>
                      <p className="text-xs text-slate-300">
                        Powered by Nexus Support Hub – level 1 questions handled by AI, escalations routed to your team.
                      </p>
                    </div>
                    <span className="inline-flex items-center gap-2 rounded-full border border-emerald-400/60 bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-200">
                      <span className="text-lg leading-none">●</span> AI Assistant Online
                    </span>
                  </div>

                  <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                    <div
                      className="flex flex-col gap-3 overflow-y-auto rounded-xl border border-slate-200 bg-white/90 p-3"
                      style={{ height: "14rem" }}
                    >
                      {chatMessages.map((message, index) => (
                        <div
                          key={`${message.from}-${index}`}
                          className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-relaxed shadow ${
                            message.from === "bot"
                              ? "self-start bg-white text-slate-900"
                              : "self-end bg-indigo-100 text-slate-900"
                          }`}
                        >
                          {message.text}
                        </div>
                      ))}
                    </div>
                    <div className="mt-3 flex flex-wrap items-center gap-3 text-xs font-semibold text-slate-700">
                      <span className="rounded-full bg-emerald-100 px-3 py-1 text-emerald-700">
                        TTS: {ttsSupported ? ttsStatus : "Unavailable in this browser"}
                      </span>
                      <span
                        className={`rounded-full px-3 py-1 ${
                          dictationSupported
                            ? "bg-indigo-100 text-indigo-700"
                            : "bg-slate-200 text-slate-600"
                        }`}
                      >
                        Voice dictation: {dictationSupported ? dictationStatus : "Not supported"}
                      </span>
                      {dictationError && (
                        <span className="rounded-full bg-red-100 px-3 py-1 text-red-700">{dictationError}</span>
                      )}
                    </div>
                    <form className="mt-4 flex flex-col gap-3 sm:flex-row" onSubmit={handleSendMessage}>
                      <Input
                        value={chatInput}
                        onChange={(e) => setChatInput(e.target.value)}
                        placeholder="Ask about timelines, documents, or next steps"
                        aria-label={t("laiTurner.chatInput", { defaultValue: "Type a message" })}
                        className="flex-1 bg-white"
                      />
                      <div className="flex items-center gap-2">
                        <Button type="submit" className="shrink-0 px-5">
                          Send
                        </Button>
                        <Button
                          type="button"
                          variant="secondary"
                          className="shrink-0 px-4"
                          onClick={isListening ? stopDictation : startDictation}
                          disabled={!dictationSupported}
                        >
                          {isListening ? "Stop voice" : "Dictate"}
                        </Button>
                      </div>
                    </form>
                    {!dictationSupported && (
                      <p className="mt-2 text-xs text-slate-600">
                        Voice capture is not available in this browser. You can still type to try the demo chat.
                      </p>
                    )}
                    {!ttsSupported && (
                      <p className="text-xs text-slate-600">
                        Text-to-speech playback is disabled because this browser does not support Web Speech synthesis.
                      </p>
                    )}
                  </div>
                </div>
              </div>

              <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                <h3 className="text-lg font-bold text-slate-900">Example of firm-specific FAQs</h3>
                <div className="mt-4 space-y-3">
                  {faqs.map((faq) => (
                    <details key={faq.question} className="group rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3">
                      <summary className="cursor-pointer list-none text-base font-semibold text-slate-900">
                        {faq.question}
                      </summary>
                      <p className="mt-2 text-sm text-slate-700">{faq.answer}</p>
                      <p className="mt-3 text-xs text-slate-500">
                        These FAQs can be replaced with real content from your intake scripts, retainer process, and jurisdiction-specific information.
                      </p>
                    </details>
                  ))}
                </div>
              </div>
            </div>
          </section>

          <section className="space-y-4">
            <h3 className="text-2xl font-bold text-slate-900">Commercial proposal for Lai & Turner Law Firm</h3>
            <p className="text-slate-700">
              Below are collaboration ideas tailored to your immigration, criminal defense, family law, estate planning, personal injury, real estate, and business matters — no payment links included in this demo.
            </p>
            <div className="grid gap-4 md:grid-cols-3">
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <h4 className="text-lg font-semibold text-slate-900">AI-powered client intake & FAQ</h4>
                <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-700">
                  <li>24/7 intake chat for immigration, criminal, and family law clients.</li>
                  <li>Automated triage and document checklists before consultations.</li>
                  <li>Centralised ticketing so your team never loses a client question.</li>
                </ul>
                <p className="mt-3 text-xs text-slate-500">
                  To explore pricing and implementation, we can schedule a short strategy call.
                </p>
              </div>

              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <h4 className="text-lg font-semibold text-slate-900">Secure, multilingual client portal</h4>
                <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-700">
                  <li>Branded login area with LAI & TURNER logo and colors.</li>
                  <li>Messaging, document sharing, and status updates in English, Mandarin, Japanese, and German.</li>
                  <li>Role-based access for attorneys, staff, and clients.</li>
                </ul>
                <p className="mt-3 text-xs text-slate-500">
                  To explore pricing and implementation, we can schedule a short strategy call.
                </p>
              </div>

              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <h4 className="text-lg font-semibold text-slate-900">Implementation & ongoing support</h4>
                <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-700">
                  <li>Discovery workshop to map your intake and case workflows.</li>
                  <li>Setup of templates and FAQs per practice area (immigration, family, criminal, estate planning, personal injury, real estate/business).</li>
                  <li>Training for your team and continuous optimisation based on real usage.</li>
                </ul>
                <p className="mt-3 text-xs text-slate-500">
                  To explore pricing and implementation, we can schedule a short strategy call.
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </Layout>
  );
};

export default LaiTurnerDemoPage;
